### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Spikatrix** [Mithil467/mitype#12]
### Subject of the issue
One of my CPU cores gets maxed out at a 100% the moment I start `mitype`

### Your environment
* Linux
* Mitype 0.1.8
* Python 2.7.12
* GNOME Terminal 3.18.3

### Steps to reproduce
 - Open `mitype`. 
 - One CPU core is maxed out at 100% until I close `mitype`

### Expected behaviour
Normal CPU usage

### Actual behaviour
100% CPU usage on one core

**Comment by Mithil467** [comment]
Thank you very much for the issue @Spikatrix.

I was able to reproduce it. The issue is because of the non blocking nature of the input in getch. A small change, setting the nodelay flag to false solved the issue.

I have tried the new changes locally. It would be very nice if you could confirm it as well by running it locally on your computer by following the instructions in the README.

**Comment by Mithil467** [comment]
Thank you very much for the issue @Spikatrix.

I was able to reproduce it. The issue is because of the non blocking nature of the input in getch. A small change, setting the nodelay flag to false solved the issue.

I have tried the new changes locally. It would be very nice if you could confirm it as well by running it locally on your computer by following the instructions in the README.

Also since this is a breaking change, @ac030540 could you please confirm that mitype is functioning fine on mac?

**Comment by Spikatrix** [comment]
I've compiled and installed `mitype` from source and the issue seems to be fixed. Thank you @Mithil467 !
