### ISSUE TITLE
Add Typing speed Score history

### ISSUE THREAD

**Issue by suhanacharya** [Mithil467/mitype#39]
**Currently there is no way to view history**
It would be great if I could see how much I'm improving using this typing test if we stored all the previous WPM, Accuracy scores in a local file.

**Solution**
At the end of a typing run, pressing a button should show the entire history as a list
Something like this:
```
| date     | time  | wpm   | Accuracy |
---------------------------------------
| 01/10/20 | 21:00 | 40.86 | 94%      |
| 01/10/20 | 21:05 | 45.34 | 95%      |   
```
And also maybe color-code each entry in the history based on 'below average', 'average', 'above-average', 'master'

**Comment by Mithil467** [comment]
Hey @suhanacharya :wave:

This seems like a good feature.
Let's first start with a basic version of this feature.
- At the end of each test, save the stats to a file `mitype.history.json` in json format with keys `date, time, id, wpm, accuracy`. Will have to see about the configuration location for appdata, for all the three major Os.
- Calling `mitype --history` should print stats formatted as you've mentioned, but directly in the terminal and not in curses.

This seems like a good first issue, since you created the issue, would you like to work on it?

**Comment by suhanacharya** [comment]
Yes, I'd love to work on it. I might need some help along the way for the implementation though because I am kind of a newbie. 😄

**Comment by suhanacharya** [comment]
@Mithil467 I have implemented Save history such that once the user completes the task its automatically stored in history.json and to view all the history we can use mitype --history

It seems to work well when I ran it on my machine (Windows) I haven't used any platform dependant code. Please review it 😄 and tell me if any changes as required.
