### ISSUE TITLE
replit not working

### ISSUE THREAD

**Issue by CorentinGaillard** [Mithil467/mitype#80]
### Subject of the issue
I clicked the [replit link](https://replit.com/@mithil467/mitype) out of curiosity, but It's missing a main.sh, so it won't run

### Your environment
Windows 10 - Edge
replit environment:
python 3.8.10 (at the time of writing)
GNU bash 4.4.20

### Expected behaviour
The program should launch automatically when the environment loads, or be a few steps from launching

### Actual behaviour
We get an error saying `unable to run, main file "main.sh" not found`.
I tried installing mitype with `pip install . --user` and then launching with `python mitype/__main__.py` but I got `ModuleNotFoundError: no module named mitype`

**Comment by Mithil467** [comment]
Thanks @CorentinGaillard  for reporting the issue!

According to Repl's [documentation](https://docs.replit.com/repls/repl-run) they no longer support running terminal apps directly in browser. The new way is to visit the source repl and hit the run button. But even then it wasn't running as somehow, the project had been classified as a `bash` project instead of `python`. Hence it was asking for a `main.sh` file. I have reconfigured it.

Thank you!
