### ISSUE TITLE
Highlight mistyped characters at the end of the test

### ISSUE THREAD

**Issue by Mithil467** [Mithil467/mitype#82]
Mistyped characters are highlighted during the test. Similarly, all the mistyped characters should be highlighted at once at the end of the test. 

**Example:**
![image](https://user-images.githubusercontent.com/44948182/123105378-0c9ffa00-d438-11eb-81dc-8f7872973720.png)

Please refer to #81 for the proposed solution mentioned [here](https://github.com/Mithil467/mitype/issues/81#issuecomment-866841208).

Thanks to @CorentinGaillard for suggesting this issue and for their contributions to it!

**Comment by Ajchler** [comment]
Hi @Mithil467, I'd like to work on this issue and I have few questions. The original issue suggested highlighting erased characters rather than mistyped, even though erasing a character doesn't always mean a missed character. Would you like me to stick to the original idea of highlighting everything you erase or should I find a way to highlight mistyped characters only (e. g. by checking if input is correct whenever it's given by the user) ?

**Comment by Mithil467** [comment]
Hey @Ajchler 👋

Thank you for your interest in contributing to mitype!
Before starting please read the Contributing guidelines.

It makes sense to mark the characters which were typed incorrectly and not all that were erased. So if a user erased a corret character, it should not be highlighted at the end of the test.

This is the line of code where we are finding the index at which the typed out text and original text differs.
https://github.com/Mithil467/mitype/blob/c66b7d779584be7ba3f3b057326784f49daf58a5/mitype/app.py#L360

We can keep track of the indexes from here.
